language: php

before_script:
  - sudo apt-get install -y ffmpeg libavcodec-extra-53
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

php:
  - 5.3
  - 5.4

script:
  - phpunit
