language: php

before_script:
  - sudo apt-get install -y ffmpeg libavcodec-extra-53
  - composer self-update
  - composer install --dev --prefer-source

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

script:
  - vendor/bin/phpunit
